/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(acquisition_and_tracking.h)                                */
/* BINDTOOL_HEADER_FILE_HASH(4748da1189e7830c995b70e7d31484c8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/acquisition_and_tracking.h>
#include <acquisition_and_tracking_pydoc.h>

void bind_acquisition_and_tracking(py::module& m)
{
    using acquisition_and_tracking = gr::gnss::acquisition_and_tracking;

    py::class_<acquisition_and_tracking,
               gr::block,
               gr::basic_block,
               std::shared_ptr<acquisition_and_tracking>>(m, "acquisition_and_tracking", D(acquisition_and_tracking))
        .def(
            py::init(&acquisition_and_tracking::make),
            py::arg("sampling_freq"),
            py::arg("dll_bw_coarse"),
            py::arg("pll_bw_coarse"),
            py::arg("dll_bw_fine"),
            py::arg("pll_bw_fine"),
            D(acquisition_and_tracking,make)
        )
        .def(
            "set_acq_params",
            &acquisition_and_tracking::set_acq_params,
            py::arg("system"),
            py::arg("id")
        )
        .def(
            "get_acq_params",
            &acquisition_and_tracking::get_acq_params,
            py::arg("system"),
            py::arg("id")
        )
        ;
}
