/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ca_code_domain.h)                                          */
/* BINDTOOL_HEADER_FILE_HASH(ac58c47049ecaddf53727b1f00f8e096)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/ca_code_domain.h>

void bind_ca_code_domain(py::module& m)
{
    using ca_code_domain = gr::gnss::ca_code_domain_e;

    py::enum_<ca_code_domain>(m, "ca_code_domain_e")
        .value("CA_CODE_DOMAIN_TIME",                ::gr::gnss::CA_CODE_DOMAIN_TIME)
        .value("CA_CODE_DOMAIN_FREQUENCY",           ::gr::gnss::CA_CODE_DOMAIN_FREQUENCY)
        .value("CA_CODE_DOMAIN_FREQUENCY_CONJUGATE", ::gr::gnss::CA_CODE_DOMAIN_FREQUENCY_CONJUGATE)
        .export_values();
}
