/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ca_symbols_to_nav_bits.h)                                  */
/* BINDTOOL_HEADER_FILE_HASH(b9b5a1f021d55ee96c74d05c1f147615)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/ca_symbols_to_nav_bits.h>
#include <ca_symbols_to_nav_bits_pydoc.h>

void bind_ca_symbols_to_nav_bits(py::module& m)
{
    using ca_symbols_to_nav_bits = gr::gnss::ca_symbols_to_nav_bits;

    py::class_<ca_symbols_to_nav_bits,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ca_symbols_to_nav_bits>>(m, "ca_symbols_to_nav_bits", D(ca_symbols_to_nav_bits))
        .def(
            py::init(&ca_symbols_to_nav_bits::make),
            D(ca_symbols_to_nav_bits,make)
        );
}
