/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(doppler_shift.h)                                           */
/* BINDTOOL_HEADER_FILE_HASH(5b3e2daaea0c1c3118b1e22f9d40db8e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/doppler_shift.h>
#include <doppler_shift_pydoc.h>

void bind_doppler_shift(py::module& m)
{
    using doppler_shift = gr::gnss::doppler_shift;

    py::class_<doppler_shift,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<doppler_shift>>(m, "doppler_shift", D(doppler_shift))
        .def(
            py::init(&doppler_shift::make),
            py::arg("x"),
            py::arg("y"),
            py::arg("z"),
            D(doppler_shift,make)
        );
}
