/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(geojson_file_sink.h)                                       */
/* BINDTOOL_HEADER_FILE_HASH(b68abd47f8f4a942f407cb725a1db943)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/geojson_file_sink.h>
#include <geojson_file_sink_pydoc.h>

void bind_geojson_file_sink(py::module& m)
{
    using geojson_file_sink = gr::gnss::geojson_file_sink;

    py::class_<geojson_file_sink,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<geojson_file_sink>>(m, "geojson_file_sink", D(geojson_file_sink))
        .def(
            py::init(&geojson_file_sink::make),
            py::arg("filename"),
            D(geojson_file_sink,make)
        );
}
