/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nav_message_decoder.h)                                     */
/* BINDTOOL_HEADER_FILE_HASH(f7930d19f59c3a6d153423ca17cee30f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/nav_message_decoder.h>
#include <nav_message_decoder_pydoc.h>

void bind_nav_message_decoder(py::module& m)
{
    using nav_message_decoder = gr::gnss::nav_message_decoder;

    py::class_<nav_message_decoder,
               gr::block,
               gr::basic_block,
               std::shared_ptr<nav_message_decoder>>(m, "nav_message_decoder", D(nav_message_decoder))
        .def(
            py::init(&nav_message_decoder::make),
            D(nav_message_decoder,make)
        )
        .def(
            "set_acq_params",
            &nav_message_decoder::set_acq_params,
            py::arg("system"),
            py::arg("id")
        )
        .def(
            "get_acq_params",
            &nav_message_decoder::get_acq_params,
            py::arg("system"),
            py::arg("id")
        )
        ;
}
