/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(navigation_system.h)                                       */
/* BINDTOOL_HEADER_FILE_HASH(551bd179a01bb1a991873d4159c2172e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/navigation_system.h>

void bind_navigation_system(py::module& m)
{
    using navigation_system = gr::gnss::navigation_system_e;

    py::enum_<navigation_system>(m, "navigation_system_e")
        .value("NAVIGATION_SYSTEM_UNDEFINED", ::gr::gnss::NAVIGATION_SYSTEM_UNDEFINED)
        .value("NAVIGATION_SYSTEM_GPS",       ::gr::gnss::NAVIGATION_SYSTEM_GPS)
        .value("NAVIGATION_SYSTEM_GALILEO",   ::gr::gnss::NAVIGATION_SYSTEM_GALILEO)
        .value("NAVIGATION_SYSTEM_GLONASS",   ::gr::gnss::NAVIGATION_SYSTEM_GLONASS)
        .export_values();
}
