/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pseudoranges_decoder.h)                                    */
/* BINDTOOL_HEADER_FILE_HASH(74fb01d350ca23a28e383ba5d8c06366)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/pseudoranges_decoder.h>
#include <pseudoranges_decoder_pydoc.h>

void bind_pseudoranges_decoder(py::module& m)
{
    using pseudoranges_decoder = gr::gnss::pseudoranges_decoder;

    py::class_<pseudoranges_decoder,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pseudoranges_decoder>>(m, "pseudoranges_decoder", D(pseudoranges_decoder))
        .def(
            py::init(&pseudoranges_decoder::make),
            py::arg("add_velocity_outputs"),
            D(pseudoranges_decoder,make)
        )
        .def(
            "set_acq_params",
            &pseudoranges_decoder::set_acq_params,
            py::arg("port"),
            py::arg("system"),
            py::arg("id")
        )
        .def(
            "get_acq_params",
            &pseudoranges_decoder::get_acq_params,
            py::arg("port"),
            py::arg("system"),
            py::arg("id")
        )
        ;
}
