/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pvt.h)                                                     */
/* BINDTOOL_HEADER_FILE_HASH(3e494822c6dc3a98dee7213d33f00d3f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/pvt.h>
#include <pvt_pydoc.h>

void bind_pvt(py::module& m)
{
    using pvt = gr::gnss::pvt;

    py::class_<pvt,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pvt>>(m, "pvt", D(pvt))
        .def(
            py::init(&pvt::make),
            py::arg("skip_zeros"),
            D(pvt,make)
        );
}








