/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rft_type.h)                                                */
/* BINDTOOL_HEADER_FILE_HASH(1b1e1140aafa5539ea9ea00250b12711)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/rft_type.h>

void bind_rft_type(py::module& m)
{
    using rft_type = gr::gnss::rft_type_e;

    py::enum_<rft_type>(m, "rft_type_e")
        .value("RFT_UNDEFINED",   ::gr::gnss::RFT_UNDEFINED)
        .value("RFT_GCS_TO_ECEF", ::gr::gnss::RFT_GCS_TO_ECEF)
        .value("RFT_ECEF_TO_GCS", ::gr::gnss::RFT_ECEF_TO_GCS)
        .export_values();
}
