/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(skip_zeros.h)                                              */
/* BINDTOOL_HEADER_FILE_HASH(7741a23dd9b8920b9871796af404a550)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/gnss/skip_zeros.h>
#include <skip_zeros_pydoc.h>

void bind_skip_zeros(py::module& m)
{
    using skip_zeros = gr::gnss::skip_zeros;

    py::class_<skip_zeros,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<skip_zeros>>(m, "skip_zeros", D(skip_zeros))
        .def(
            py::init(&skip_zeros::make),
            D(skip_zeros,make)
        );
}
